

#ifndef _AFL_COVERAGE_STATE_BITS_H
#define _AFL_COVERAGE_STATE_BITS_H

#define MASK_EDGE_REACHABLE (1 << 31)
#define MASK_FUNCTION_REACHABLE (1 << 0)
#define MASK_REACHABLE_BITS (MASK_EDGE_REACHABLE | MASK_FUNCTION_REACHABLE)
#define MASK_NO_REACHABLE_BITS (~MASK_REACHABLE_BITS)

#endif // _AFL_COVERAGE_STATE_BITS_H